### ISSUE TITLE
SpoutReceiver: OpenGL error 1280 at top endDraw(): invalid enumerant

### ISSUE THREAD

**Issue by maybites** [leadedge/SpoutProcessing#1] opened 2016-01-31 17:19 UTC
Using Windows 10
AMD radeon r9 m370x latest drivers
64bit

**Comment by leadedge** [comment] 2016-02-01 02:59
Error 1280 is "GL_INVALID_ENUM", so it could be something to do with an unsupported enum value for that particular video card driver. But not necessarily. My chances of finding the cause of the error are slim unless I can reproduce the problem, but I will think about it and there might be some tests that could isolate it.

**Comment by maybites** [comment] 2016-02-06 09:44
good news: Option 2 and 3 are working!!

With the latest commit 9a09b66 I get a new error for option1:
OpenGL error 1282 at top endDraw(): invalid operation

**Comment by leadedge** [comment] 2016-03-29 13:09
Resolved by using a PGraphics object within the Spout class

**Closed as completed by leadedge** 2016-03-29 13:09 UTC
